# Generated by Django 6.0.1 on 2026-02-03 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_alter_product_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MPPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_expiration', models.DateTimeField(editable=False)),
                ('expired', models.BooleanField(default=False, editable=False)),
                ('value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('preference_id', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('init_point', models.URLField(blank=True, editable=False, max_length=500, null=True)),
                ('payer_email', models.EmailField(blank=True, editable=False, max_length=254, null=True)),
                ('finalized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MpPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('finalized', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.mppreference')),
            ],
        ),
    ]
