# Generated by Django 5.2.5 on 2026-01-13 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mppreference',
            old_name='paid',
            new_name='finalized',
        ),
        migrations.RemoveField(
            model_name='mppreference',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='mppreference',
            name='payer_email',
        ),
        migrations.RemoveField(
            model_name='mppreference',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='cart',
            name='preference',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.mppreference'),
        ),
        migrations.CreateModel(
            name='MpPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('finalized', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.mppreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
