# Generated by Django 5.2.5 on 2026-01-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscountCupom',
            new_name='DiscountCoupon',
        ),
    ]
