# Generated by Django 5.2.5 on 2026-01-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_paid_mppreference_finalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mppreference',
            name='payer_email',
            field=models.EmailField(blank=True, editable=False, max_length=254, null=True),
        ),
    ]
