# Generated by Django 6.0.1 on 2026-02-03 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('store', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='preference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.mppreference'),
        ),
        migrations.DeleteModel(
            name='MpPayment',
        ),
        migrations.DeleteModel(
            name='MPPreference',
        ),
    ]
