# Generated by Django 6.0.1 on 2026-02-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cart_preference_delete_mppayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmessage',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='SupportChannel',
        ),
        migrations.DeleteModel(
            name='SupportMessage',
        ),
    ]
