# Generated by Django 6.0.1 on 2026-01-24 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_mppreference_payer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='preference',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='store.mppreference'),
        ),
        migrations.AlterField(
            model_name='mppreference',
            name='expired',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='mppreference',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
