# Generated by Django 5.2.5 on 2025-09-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cartitem_unique_together_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
