# Generated by Django 6.0.1 on 2026-01-26 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_reserved_stock_alter_cart_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='preference',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.mppreference'),
        ),
    ]
