# Generated by Django 6.0.1 on 2026-01-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartitem_is_reserved_alter_cart_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reserved_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
