# Generated by Django 5.2 on 2025-10-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_client_cpf_alter_client_email_and_more'),
        ('store', '0006_order_total_price_alter_order_status'),
    ]

    operations = [
    ]
