# Generated by Django 5.2.5 on 2025-12-11 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_total_price_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='passed_continue_to_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='passed_payment_step',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='MPPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_expiration', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=200)),
                ('expired', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
            ],
        ),
    ]
