# Generated by Django 5.2 on 2025-10-21 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_merge_20251020_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcupom',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='used_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
