# Generated by Django 6.0.1 on 2026-01-28 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_supportchannel_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportchannel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
