# Generated by Django 5.2.5 on 2025-12-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_passed_continue_to_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mppreference',
            name='init_point',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mppreference',
            name='preference_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mppreference',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mppreference',
            name='payment_method',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
