# Generated by Django 5.2.5 on 2025-12-13 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_mppreference_init_point_mppreference_preference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mppreference',
            name='cart',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
        migrations.AlterField(
            model_name='mppreference',
            name='init_point',
            field=models.URLField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mppreference',
            name='payment_method',
            field=models.CharField(blank=True, default=None, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mppreference',
            name='preference_expiration',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='mppreference',
            name='preference_id',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
